# Generated by Django 5.1 on 2024-08-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
