# Generated by Django 5.1 on 2024-08-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reco', '0002_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceVer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('face', models.ImageField(upload_to='reco/')),
            ],
        ),
    ]
