# Generated by Django 5.1 on 2024-08-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FaceVer',
        ),
    ]
