# Generated by Django 5.1 on 2024-10-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reco', '0008_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('face_embedding', models.JSONField()),
            ],
        ),
    ]
