# Generated by Django 5.1 on 2024-09-25 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_profile_name_userdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
