# Generated by Django 5.1 on 2024-09-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='profile_histories', to='api.news'),
        ),
    ]
