# Generated by Django 5.1 on 2024-10-08 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Face',
        ),
    ]
