# Generated by Django 5.1 on 2024-10-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='primary_images/'),
        ),
    ]
