# Generated by Django 5.1 on 2024-10-17 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_profile_primary_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='primary_image',
        ),
    ]
