# Generated by Django 5.1 on 2024-10-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_profile_primary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='face_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
