# Generated by Django 5.1 on 2024-10-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_profile_face_embedding_userface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userface',
            old_name='embedding',
            new_name='face_embedding',
        ),
    ]
